# Generated by Django 5.1.6 on 2025-02-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('emil', models.EmailField(max_length=254)),
                ('dep', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
