# Generated by Django 5.1.6 on 2025-03-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='nunber',
            new_name='number',
        ),
    ]
