# Generated by Django 5.1.6 on 2025-03-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_nunber_store_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='passord',
            new_name='password',
        ),
    ]
