# Generated by Django 5.1.6 on 2025-03-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_passord_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emil',
            new_name='email',
        ),
    ]
